M1T2-5_fix_delet_alaram_and_console
js-tasks-ru/jsbasic-20240219_bonezscaut pull request #3
Opened 2024-03-14 19:09 UTC by Bonezscaut

убрал консольлоги и алерты, почему-то не получается залить таски 2-5(( с чем это может быть связано?

2024-03-14 19:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-14 19:18 UTC, Bonezscaut commented
понял, вот пытаюсь сделать, уже как только не переделывал(

2024-03-14 19:43 UTC, Bonezscaut commented
гхм, прошли тесты)

2024-03-18 10:42 UTC, Bonezscaut commented
<img width="1121" alt="Screenshot 2024-03-18 at 14 41 55" src="https://github.com/js-tasks-ru/jsbasic-20240219_bonezscaut/assets/161596507/ac5eb7b2-5e8f-445a-87a8-a1019df8cd55">
Дайте пожалуйста обратную связь, чтобы забрать новые задачи

2024-03-18 10:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-18 10:45 UTC, koalex commented
> <img alt="Screenshot 2024-03-18 at 14 41 55" width="1121" src="https://private-user-images.githubusercontent.com/161596507/313643219-ac5eb7b2-5e8f-445a-87a8-a1019df8cd55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTg5MzIsIm5iZiI6MTcxMDc1ODYzMiwicGF0aCI6Ii8xNjE1OTY1MDcvMzEzNjQzMjE5LWFjNWViN2IyLTVlOGYtNDQ1YS04N2E4LWExMDE5ZGY4Y2Q1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxOFQxMDQzNTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZjJiNGI1OTE4YWE1NjdkMzIxZTQ5ZDMxMzY2NGFjODkzYWEyMjk4NzQzODRkYTJiNTE3MTZmZmJlZjM2Nzk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Fr5wVEJwBaa5_zxIMmv2x7dKs7IpSFWciOlyo1WDu1c"> Дайте пожалуйста обратную связь, чтобы забрать новые задачи

введите `git config pull.rebase true` а затем `git pull upstream master`

2024-03-18 10:49 UTC, koalex requested changes
Нет решения для **2-1**, **2-2**, **2-3**, **3-1**, **3-2**, **3-3**, **3-4**, **3-5**

2024-03-18 10:49 UTC, koalex commented on 1-module/3-task/index.js
> +console.log(ucFirst('вася')); // Вася
Удаляйте `console.log`-и

2024-03-18 10:49 UTC, koalex commented on 1-module/4-task/index.js
> +console.log(checkSpam('1XbeT now'));
Удаляйте `console.log`-и

2024-03-18 10:51 UTC, Bonezscaut commented
> Нет решения для **2-1**, **2-2**, **2-3**, **3-1**, **3-2**, **3-3**, **3-4**, **3-5**

Да, их добавил, после пул реквеста по старым, тогда сейчас все сделаю что добавлены и залью

2024-03-18 20:54 UTC, closed without merging