M4_alltasks
js-tasks-ru/jsbasic-20240219_bonezscaut pull request #6
Opened 2024-03-19 18:00 UTC by Bonezscaut

Решение всех 3х заданий из модуля 4

2024-03-19 18:01 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-19 18:02 UTC, Bonezscaut commented
проверил, тесты локально проходят, вылетает только ошибка -"Error: Process completed with exit code 1." с чем она может быть связана?

2024-03-21 10:38 UTC, koalex requested changes
Исправить замечания **4-1** и **4-2**

2024-03-21 10:38 UTC, koalex commented on 4-module/1-task/index.js
> +document.body.appendChild(createFriendsList(friends));
Удалить эту строку. Она ломает тесты т.к. в тестах нет настоящего body

2024-03-21 10:38 UTC, koalex commented on 4-module/2-task/index.js
> +let table = document.getElementById('table');
Удалить стр8 и стр9

2024-03-22 09:27 UTC, Bonezscaut commented on 4-module/1-task/index.js
> +document.body.appendChild(createFriendsList(friends));
поправил

2024-03-22 09:27 UTC, Bonezscaut commented on 4-module/2-task/index.js
> +let table = document.getElementById('table');
поправил

2024-03-22 09:27 UTC, jsru commented
Добавляю преподавателя (@koalex) для код-ревью.

2024-03-22 10:16 UTC, koalex approved these changes

2024-03-22 10:17 UTC, merged